---
- hosts: mywebservers
  become: yes
  tasks:
  - name: install java on ubuntu nodes
    apt:
      name:  "{{myjavapackageonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"

  - name: install java in RedHat nodes
    yum:
      name: "{{myjavapackageonredhat}}"
      state: present
    when: ansible_os_family =="RedHat"