---
- hosts: mywebservers
  become: yes
  tasks:
  - name: i wanna to execute linux command
    command: hostname -f
    register: myresult

  - name: i wanna display my first task result
    debug:
      msg: "{{myresult}}"

  - name: install tree
    apt:
      name: tree
      state: present

    when: myresult.stderr==""
  
  - name: install git
    apt:
      name: git
      state: present

    when: myresult.stderr!=""