---
- hosts: 172.31.8.215
  become: yes
  vars: 
     myvar1: git
     myvar2: tree
     myvar3: wget
  tasks:
  - name: i want to display myvar1
    debug:
        msg: "{{ myvar1 }}"

    #ignore-error: yes