---
- hosts: 172.31.2.70
  become: yes
  tasks:
  - name: i want to install web server only on ubuntu
    apt:
      name: "{{mywebserver}}"
      state: present

    when: ansible_os_family=="Debian"

  - name: i want to install web server only on redhat
    yum:
      name: "{{mywebserver}}"
      state: present
    when: ansible_os_family=="RedHat"

  - name: start the sevice
    service:
      name: "{{mywebserver}}"
      state: started
    when: ansible_os_family=="RedHat"

  - name: start the sevice
    service:
      name: "{{mywebserver}}"
      state: started
    when: ansible_os_family=="Debian"

